# Site settings
title: mickael-baron.fr
description: >- # this means to ignore newlines until "baseurl:"
  Site web personnel de Mickael BARON concernant mes découvertes sur les différentes technologies du moment Java Docker VueJS Eclipse Services WebSemantic
baseurl: ""  # the subpath of your site, e.g. /blog
url: https://mickael-baron.fr 
repo: https://github.com/mickaelbaron/mickaelbaron.github.io
repository: https://github.com/mickaelbaron/mickaelbaron.github.io
aboutme: Je suis <b>Mickaël BARON</b> Ingénieur de Recherche en Informatique <i class="fas fa-laptop"></i> à l'<a target="_blank" href="https://www.ensma.fr/">ISAE-ENSMA</a> et membre du laboratoire <a target="_blank" href="https://www.lias-lab.fr">LIAS</a> le jour <i class="fas fa-sun"></i><br>Veilleur Technologique la nuit <i class="fas fa-moon"></i><br><i class="fas fa-heart"></i> &#35;Java <i class="fab fa-java"></i> &#35;Container <i class="fab fa-docker"></i> &#35;VueJS <i class="fab fa-vuejs"></i> &#35;Services &#35;WebSemantic
github_username: mickaelbaron

# Build settings
markdown: kramdown
plugins:
 - jekyll-feed

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: true
      start_line: 1

# Author Info
author:
  name     : Mickael BARON
  image    : ./images/mbaron.jpg
  email    : baron.mickael@gmail.com
  github   : mickaelbaron
  twitter  : mickaelbaron
  linkedin : mickaelbaron

# Authors Info
authors:
  diabatem:
    name    : Mahamadou DIABATE
    website : https://twitter.com/DiabatMahamado1
  martinif:
    name    : Frédéric MARTINI
    website : https://www.developpez.net/forums/u1195/adiguba/

# Collections
collections:
  javaee:
    output: true
    permalink: /javaee/:name
  java:
    output: true
    permalink: /java/:name
  soa:
    output: true
    permalink: /soa/:name
  eclipse:
    output: true
    permalink: /eclipse/:name
  modeling:
    output: true
    permalink: /modeling/:name
  data-nosql:
    output: true
    permalink: /data-nosql/:name
  web:
    output: true
    permalink: /web/:name
  divers:
    output: true
    permalink: /divers/:name

# Default values for collections
defaults:
  - scope:
      path: ""
      type: "soa"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "javaee"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "java"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "eclipse"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "modeling"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "divers"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "data-nosql"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "web"
    values:
      layout: "resource"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Posts default Permalink
permalink: blog/:year/:month/:day/:title

# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
